name: Trees Building and Testing
run-name: ${{ github.actor }} is testing out Trees

on:
  push:
    paths:
      - lib/src/main/kotlin/libTree/trees/AVLTree.kt
      - lib/src/test/kotlin/libTreeTests/AVLTreeTest.kt
      - lib/src/test/kotlin/libTreeTestsUtils/AVLTreeTestsUtils.kt
  pull_request:
    paths:
      - lib/src/main/kotlin/libTree/trees/AVLTree.kt
      - lib/src/test/kotlin/libTreeTests/AVLTreeTest.kt
      - lib/src/test/kotlin/libTreeTestsUtils/AVLTreeTestsUtils.kt

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yutailang0119/action-ktlint@v4
        with:
          report-path: build/*.xml
          ignore-warnings: true
        continue-on-error: false

